//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormationDotNetForms
{
    using System;
    using System.Collections.Generic;
    
    public partial class Magasin
    {
        public int id_magasin { get; set; }
        public string nom { get; set; }
        public Nullable<float> prix { get; set; }
        public string poids { get; set; }
        public string quantite { get; set; }
        public string tax { get; set; }
    }
}
