//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormationDotNetFormsEvaluation
{
    using System;
    using System.Collections.Generic;
    
    public partial class Heros
    {
        public int id_hero { get; set; }
        public string nom { get; set; }
        public string prenom { get; set; }
        public string specialite { get; set; }
        public string classe { get; set; }
        public Nullable<int> lvl { get; set; }
        public Nullable<int> puissance { get; set; }
        public Nullable<int> nbMissionReussi { get; set; }
        public Nullable<int> reputation { get; set; }
    }
}
