//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormationDotNetFormsEvaluation
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventaire
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Inventaire()
        {
            this.Heros = new HashSet<Heros>();
        }
    
        public int id_inventaire { get; set; }
        public string objetNom { get; set; }
        public Nullable<int> objetLvl { get; set; }
        public Nullable<int> objetQuantite { get; set; }
        public string objetDescription { get; set; }
        public Nullable<float> objetPrix { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Heros> Heros { get; set; }
    }
}
